version: '3'

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./persisted:/app/persisted
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file: .env.db
    environment:
      POSTGRES_USER: lemonbot-warns
    volumes:
      - ./persisted/db:/var/lib/postgresql/data
    restart: unless-stopped
